### ISSUE TITLE
Fails to build because module OrderTaking.PlaceOrder.Implementation is internal

### ISSUE THREAD

**Issue by kentcb** [swlaschin/DomainModelingMadeFunctional#13]
Maybe I'm missing something dumb, but if I grab the code as-is, I can't build using latest VS2019 or VS2019 preview:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	FS0410	The type 'CheckedAddress' is less accessible than the value, member or type 'val checkAddressExists : unvalidatedAddress:UnvalidatedAddress -> AsyncResult<Implementation.CheckedAddress,Implementation.AddressValidationError>' it is used in.	OrderTaking	C:\Users\Kent\Repository\DomainModelingMadeFunctional\src\OrderTaking\PlaceOrder.Api.fs	46	Active
Error	FS0410	The type 'AddressValidationError' is less accessible than the value, member or type 'val checkAddressExists : unvalidatedAddress:UnvalidatedAddress -> AsyncResult<Implementation.CheckedAddress,Implementation.AddressValidationError>' it is used in.	OrderTaking	C:\Users\Kent\Repository\DomainModelingMadeFunctional\src\OrderTaking\PlaceOrder.Api.fs	46	Active
Error	FS0410	The type 'HtmlString' is less accessible than the value, member or type 'val createOrderAcknowledgmentLetter : pricedOrder:PricedOrder -> Implementation.HtmlString' it is used in.	OrderTaking	C:\Users\Kent\Repository\DomainModelingMadeFunctional\src\OrderTaking\PlaceOrder.Api.fs	56	Active
Error	FS0410	The type 'OrderAcknowledgment' is less accessible than the value, member or type 'val sendOrderAcknowledgment : orderAcknowledgement:Implementation.OrderAcknowledgment -> Implementation.SendResult' it is used in.	OrderTaking	C:\Users\Kent\Repository\DomainModelingMadeFunctional\src\OrderTaking\PlaceOrder.Api.fs	61	Active
Error	FS0410	The type 'SendResult' is less accessible than the value, member or type 'val sendOrderAcknowledgment : orderAcknowledgement:Implementation.OrderAcknowledgment -> Implementation.SendResult' it is used in.	OrderTaking	C:\Users\Kent\Repository\DomainModelingMadeFunctional\src\OrderTaking\PlaceOrder.Api.fs	61	Active
```

This makes sense because functions in the (`public`) `OrderTaking.PlaceOrder.Api` module are returning types from the (`internal`) `OrderTaking.PlaceOrder.Implementation` module. Was this a recent improvement to the F# compiler to catch this case?

For now, I can simply remove the `internal` modifier and it builds.

**Comment by jasondown** [comment]
@kentcb Another option to keep the actual implementation internal is to change `module internal OrderTaking.PlaceOrder.Implementation` to `module OrderTaking.PlaceOrder.ImplementationTypes` (for all the types that are declared in that file) and then in section 2 where the actual implementation of the various functions takes place, create an internal module called `module internal Implementation` (you'll have to define it like so `module internal Implementation =` and then indent everything underneath that).

Once you've done that, you just need to change the `OrderTaking.PlaceOrder.Api` module to qualify the types with `ImplementationTypes` (e.g. `ImplementationTypes.CheckedAddress`). You'll also have to change the `placeOrderApi` workflow function (at the bottom of the file) to be like so:
```fsharp
let placeOrderApi : PlaceOrderApi =
...
    let workflow = 
                ImplementationTypes.Implementation.placeOrder 
```

This exposes the types as public, but keeps the actual functions using the types as internal.

To answer your question about the compiler improvement, yes, it was a change (in 4.1 I think) to turn that into a compiler error. You can also trigger a similar compiler warning (not error) if you were to leave the code as is and add the following line as a type alias in PlaceOrder.Api:

```fsharp
type CheckAddressExists = Implementation.CheckAddressExists
```

**Comment by jasondown** [comment]
I've created a PR for this (I guess I did it wrong because it opened a new issue, oops). The PR is issue #17

**Comment by swlaschin** [comment]
Thanks for catching this and thanks for making a PR. I decided to handle this differently and just make the dummy implementations internal as well (which they should be anyway). So I will close the PR, but thanks again!
