### ISSUE TITLE
Question: is it still the recommended way to do dependency parameterization?

### ISSUE THREAD

**Issue by Jason5Lee** [swlaschin/DomainModelingMadeFunctional#15]
In this repo, you generally used dependency parameterization as the dependency injection strategy without using interfaces or functions record, but in your recent blog post, you recommended dependency rejection over other methods. So for the enterprise-level application, which is a better way?

**Comment by swlaschin** [comment]
Good question! In general, I would start with dependency rejection as much as possible, and then add dependency parameterization after that.  Starting with dependency rejection means that testing is much easier and you don't have the complication of async everywhere.

But... the example I used in the book was very heavy on I/O with not much business logic, and so dependency rejection was not very applicable in that case.  Hope this helps!

**Comment by Jason5Lee** [comment]
Thanks for answering.
