### ISSUE TITLE
Domain Modelling Made Functional Book

### ISSUE THREAD

**Issue by SJGowen** [swlaschin/DomainModelingMadeFunctional#16]
Hi,

Domain Modelling Made Functional Book

Just bought the book from amazon.co.uk. Could you please post the diagram that is meant to be on the top of page 18! The diagram that is in my copy ‘Book version: P1.0-January 2018’ has the same diagram on page 18 as is on page 17 i.e. the ‘Problem space (real world) - Solution space (domain world)’. I have looked around and can find no mention of this error or the correct diagram.

Best regards

Stephen

**Comment by SJGowen** [comment]
I have also created a duplicate issue on : https://devtalk.com/books/domain-modeling-made-functional/errata but as I can see no other errata on that site thought that this site might give me a better response...

**Comment by swlaschin** [comment]
Sorry about that.  The two Problem space/Solution diagrams are meant to be

* [normal mapping](https://www.dropbox.com/s/0ofv8un5uxs0gcq/order-taking-domains2.pdf?dl=0)
* [with legacy system](https://www.dropbox.com/s/h3htu0yhswujwo1/order-taking-domains3.pdf?dl=0)

Thanks!

**Comment by swlaschin** [comment]
I also added something to the errata page on the PragProg site.
