### ISSUE TITLE
asyncResult not working

### ISSUE THREAD

**Issue by sowedasig** [swlaschin/DomainModelingMadeFunctional#3]
Hello Scott!
I have been stuck with the "validateOrder function" in the "PlaceOrder.Implementation.fs" file for a while and I hope to get some help from you. 
I tried to post my issue in prag prog "The website where I got your book from", but it seems like some legislation in the USA has caused them to make the forum unavaillable. 

Bellow is the piece of code that seems not to be working:

let validateOrder : ValidateOrder = 

    fun checkProductCodeExists checkAddressExists unvalidatedOrder ->

        printfn "IN validate order unvalidatedOrder = %A" unvalidatedOrder

        printfn "IN validate order unvalidatedOrder.OrderId = %A" unvalidatedOrder.OrderId

        asyncResult {

            //printfn "IN validate order customerInfo = %A" customerInfo

            let! orderId = 
                unvalidatedOrder.OrderId 
                |> toOrderId
                |> AsyncResult.ofResult

            printfn "orderId = %A" orderId

            let! customerInfo = 
                let unvalidateCustomerInfo = unvalidatedOrder.CustomerInfo 
                unvalidateCustomerInfo
                |> toCustomerInfo
                |> AsyncResult.ofResult

            let! checkedShippingAddress = 
                let unvalidateShippingAddress = unvalidatedOrder.ShippingAddress 
                unvalidatedOrder.ShippingAddress 
                |> toCheckedAddress checkAddressExists

            let! shippingAddress = 
                checkedShippingAddress 
                |> toAddress 
                |> AsyncResult.ofResult
            let! checkedBillingAddress = 
                unvalidatedOrder.BillingAddress 
                |> toCheckedAddress checkAddressExists
            let! billingAddress  = 
                checkedBillingAddress
                |> toAddress 
                |> AsyncResult.ofResult
            let! lines = 
                unvalidatedOrder.Lines 
                |> List.map (toValidatedOrderLine checkProductCodeExists) 
                |> Result.sequence // convert list of Results to a single Result
                |> AsyncResult.ofResult

            let validatedOrder : ValidatedOrder = {
                OrderId  = orderId 
                CustomerInfo = customerInfo 
                ShippingAddress = shippingAddress 
                BillingAddress = billingAddress  
                Lines = lines 
            }

            return validatedOrder 
        }

This instruction

let! orderId = 
                unvalidatedOrder.OrderId 
                |> toOrderId
                |> AsyncResult.ofResult

 runs the unvalidatedOrder.OrderId  |> toOrderId function with no problem
 then it gets stuck at  |> AsyncResult.ofResult. 

I would appreciate if you could help me figure out what the issue is with 
 AsyncResult.ofResult as I feel like it is there that everything is stuck.

**Comment by sowedasig** [comment]
Can anyone please help me with this issue? I have been stuck on it for months.

**Comment by allentiak** [comment]
Just curious... Is this one fixed by #10?

**Comment by swlaschin** [comment]
@sowedasig Sorry I never got back to you on this. I hope you got it working in the end! 
Please reopen if you still have problems.
