### ISSUE TITLE
Porting to .NET Core/Standard

### ISSUE THREAD

**Issue by HoraceGonzalez** [swlaschin/DomainModelingMadeFunctional#4]
Hi, Scott!

Would you be interested in porting this code to .net core/standard? I've received some questions on the F# slack group about build errors running this on mac/linux w/t ionide. I noticed the projects are targeting net461 and thought this may be responsible for some of the grief.  

I'd be willing to help with this.

**Comment by swlaschin** [comment]
I'd very happy to port this to .NET Standard, now that things have settled down.  If you're willing to do this, I'd be very grateful!

**Comment by svdHero** [comment]
Any progress on this? I am totally new to F# and its toolchain. Running `build.cmd` in my Windows 8.1 command line window completes successfully. However, I get the following error when opening the solution file in Visual Studio 2019:

```
07.01.2020 14:38:37	Critical	Some of the projects might not be read correctly. You may disable solution loading from disk or do that for certain projects.|   
Project 'OrderTaking' load failed:
	The SDK 'Microsoft.NET.Sdk' specified could not be found.  W:\GIT_WORKSPACES\VisualStudio2019_WS\DomainModelingMadeFunctional\src\OrderTaking\OrderTaking.fsproj at (0:0)Project 'OrderTakingEvolved' load failed:
	The SDK 'Microsoft.NET.Sdk' specified could not be found.  W:\GIT_WORKSPACES\VisualStudio2019_WS\DomainModelingMadeFunctional\src\OrderTakingEvolved\OrderTakingEvolved.fsproj at (0:0)
```

Unfortunately I do not understand how all the SDK and runtime settings in

- `global.json`
- `DomainModelingMadeFunctional.sln`
- `paket.dependencies`
- `paket.lock`
- `OrderTaking.fsproj`

affect each other. Like said, I am totally new to F# and I know nothing about Paket.

On my system, I have `Microsoft.NET Framework 4.6.1 SDK`, `Microsoft.NET Framework 4.7.2 SDK` and `Microsoft.NET Core SDK 3.1.100` installed.

However, I'd like to work platform independently and go down the .NET Core path.

**Comment by rohancragg** [comment]
I get lots of errors running build.cmd on Windows 10:

The errors all seem to relate to netstandard.

...\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.fs(2,19): error FS0074: The type referenced through 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard'. [...\src\OrderTaking\OrderTaking.fsproj]

I'm not sure how and where I should reference it as advised in the error message.

**Comment by rohancragg** [comment]
> I get lots of errors running build.cmd on Windows 10:
> 
I should add that I get these errors with the source code download from the book vendor website: https://pragprog.com/titles/swdddf/source_code

I am now able to get build to run without errors as long as I do the following (to match my installed dotnet SDK):

build.fsx line 16:
> let dotnetcliVersion = "3.1.100"

global.json - line3 :
> "version": "3.1.100"

I assume I could also get this to work if I install version 2.4.1 of the dotnet SDK - I've not tried that yet but that may work for other readers...

I have a commit here that demonstrates the above:
https://github.com/rohancragg/DomainModelingMadeFunctional/commit/0da29c11a3416bcc9ad61bc69f354cb167334dd8

**Comment by HoraceGonzalez** [comment]
Hi there, @rohancragg & @svdHero. 

I'm getting ready to send a PR to upgrade the project to dotnet core 3.1. I'm on ubuntu, so I was unable to test this on Windows. Would you mind cloning my fork (below) and building? The branch name is `dotnet-core-3.1.101`

https://github.com/HoraceGonzalez/DomainModelingMadeFunctional/tree/dotnet-core-3.1.101

EDIT: here's the PR: https://github.com/swlaschin/DomainModelingMadeFunctional/pull/12

**Comment by HoraceGonzalez** [comment]
https://github.com/swlaschin/DomainModelingMadeFunctional/pull/12 has been merged!

**Comment by svdHero** [comment]
Sorry for the delay. Do you still need a windows guinea pig? I can test it later today.

**Comment by svdHero** [comment]
I can confirm that the master builds on Windows 8.1 and that I can open and build it with Visual Studio 2019 without any problems. Thanks @HoraceGonzalez for fixing this. :+1:

**Comment by swlaschin** [comment]
Thank you everyone for your help!

**Comment by rohancragg** [comment]
Also builds on Windows 10 :-)

**Comment by HoraceGonzalez** [comment]
Wow. .net core is truly xplat these days. Very nice.
