### ISSUE TITLE
How to interact with presistent?

### ISSUE THREAD

**Issue by unliftedq** [swlaschin/DomainModelingMadeFunctional#9]
DDD told us db is not important, it's none of the domain's bussiness, it's infrastructure side. That's fine and reasonable. But most ddd demos just ignore the implementation of presistent and which confused me most.  How to design my table besides domain and in which layer my dbcontext works.
So the problem come to I learned DDD but I don't know how to save my data.

**Comment by swlaschin** [comment]
Closing due to age of issue. I hope you solved your problem!
